import { DIFFICULTY_OPTIONS, LAYOUT_OPTIONS, QUALITY_OPTIONS, RULE_OPTIONS, type MenuOption } from './player-profile';

const options = (list: readonly MenuOption[]) =>
  list.map((option) => `<option value="${option.value}">${option.label}</option>`).join('');
export function icon(name: string, size = 20) {
  const paths: Record<string, string> = {
    sound: '<path d="m11 5-6 4H2v6h3l6 4V5Z"/><path d="M15.5 8.5a5 5 0 0 1 0 7M19 5a10 10 0 0 1 0 14"/>',
    mute: '<path d="m11 5-6 4H2v6h3l6 4V5Z"/><path d="m17 9 5 6m0-6-5 6"/>',
    full: '<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',
    settings:
      '<path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z"/><path d="m9 3 6 0 .5 3 2 1 2.8-1 3 5-2.3 2v2l2.3 2-3 5-2.8-1-2 1-.5 3H9l-.5-3-2-1-2.8 1-3-5 2.3-2v-2L.7 11l3-5 2.8 1 2-1Z" transform="translate(2 0) scale(.83)"/>',
    arrow: '<path d="M5 12h14m-5-5 5 5-5 5"/>',
    chevron: '<path d="m8 10 4 4 4-4"/>',
    robot:
      '<rect x="4" y="7" width="16" height="13" rx="4"/><path d="M12 7V3m-2 0h4M1 12v4m22-4v4M8 12v2m8-2v2m-7 3h6"/>',
    users:
      '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-3.87M16 3a4 4 0 0 1 0 8"/><circle cx="9" cy="7" r="4"/>',
    local: '<rect x="3" y="5" width="18" height="14" rx="3"/><path d="M7 12h4m-2-2v4m6-3h.01M18 14h.01"/>',
    mouse: '<rect x="6" y="2" width="12" height="20" rx="6"/><path d="M12 2v7M6 9h12"/>',
    target: '<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3"/>',
    reset: '<path d="M3 10a9 9 0 1 1 2.6 8.5M3 3v7h7"/>',
    help: '<circle cx="12" cy="12" r="9"/><path d="M9.1 9a3 3 0 0 1 5.8 1c0 2-3 2-3 4m.1 3h.01"/>',
    copy: '<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',
    close: '<path d="m6 6 12 12M6 18 18 6"/>',
    check: '<path d="m5 12 4 4L19 6"/>',
    trophy: '<path d="M8 3h8v8a4 4 0 0 1-8 0V3Zm0 2H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4m-4 3v6m-5 0h10"/>',
    cue: '<path d="m4 20 15-15 1-3-3 1L2 18l2 2Z"/><path d="m13 7 4 4"/>',
    camera:
      '<rect x="3" y="6" width="18" height="14" rx="3"/><path d="m8 6 2-3h4l2 3"/><circle cx="12" cy="13" r="4"/>',
    coin: '<circle cx="12" cy="12" r="9"/><path d="M12 6v12m-3-9h4a2 2 0 0 1 0 4h-2a2 2 0 0 0 0 4h4"/>',
    chalk: '<path d="m5 9 7-4 7 4v8l-7 4-7-4Z"/><path d="m5 9 7 4 7-4m-7 4v8"/>',
    clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    bolt: '<path d="m13 2-9 12h7l-1 8 10-13h-7l0-7Z"/>',
    snow: '<path d="M12 2v20M3.3 7l17.4 10M3.3 17 20.7 7M9 4l3 3 3-3M9 20l3-3 3 3M3 10l4-1-1-4m12 14-1-4 4-1M3 14l4 1-1 4m12-14-1 4 4 1"/>',
    shield: '<path d="m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6l8-4Z"/><path d="m8 12 3 3 5-6"/>',
    spark: '<path d="m12 3 2.3 6.7L21 12l-6.7 2.3L12 21l-2.3-6.7L3 12l6.7-2.3L12 3Z"/>',
  };
  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.target}</svg>`;
}
/** Online entries are hidden when this build has no room server. */
export function shell({ online }: { online: boolean }) {
  const onlineHidden = online ? '' : ' hidden';
  return `
  <main class="club">
    <section class="game-stage" aria-label="Pool game">
      <div id="scene"></div><div class="stage-vignette"></div>
      <header class="hud">
        <button class="brand" id="play-nav" title="Main menu" aria-label="Open main menu"><span class="brand-ball"><span>8</span></span></button>
        <div class="scoreboard" id="scoreboard" aria-label="Scoreboard">
          <div class="player active" id="player-0"><div class="avatar" id="avatar-0">Y</div><div class="player-detail"><div class="player-heading"><strong id="name-0">You</strong><b id="score-0" class="player-score">0</b></div><div id="roster-0" class="team-roster" aria-label="Team one players" hidden></div><div class="ball-rack" id="rack-0"></div><div class="buffs" id="buffs-0"></div></div><span id="turn-0" class="turn-light" aria-label="Current player"></span></div>
          <div class="player player-two" id="player-1"><span id="turn-1" class="turn-light" hidden aria-label="Current player"></span><div class="player-detail"><div class="player-heading"><strong id="name-1">The Regular</strong><b id="score-1" class="player-score">0</b></div><div id="roster-1" class="team-roster" aria-label="Team two players" hidden></div><div class="ball-rack" id="rack-1"></div><div class="buffs" id="buffs-1"></div></div><div class="avatar" id="avatar-1">${icon('cue')}</div></div>
        </div>
        <div class="header-actions"><span class="level-badge" id="rules-badge" title="Rule set for this session">Old Rules</span><span class="level-badge" id="level-badge">LV 1</span><span class="portal-badge" id="portal-badge" hidden title="Portal turns remaining"></span><button class="icon-button" id="sound-toggle" aria-label="Mute sound" title="Sound">${icon('sound')}</button><button class="icon-button" id="settings-button" aria-label="Settings" title="Settings">${icon('settings')}</button></div>
      </header>
      <div class="stage-tools"><button class="icon-button fps-button" id="fps-view" aria-label="Return to shooting view" aria-pressed="true" title="Shooting view · F">FPS</button><button class="icon-button" id="camera-toggle" aria-label="Switch to overhead view" title="Overhead view · V">${icon('camera', 18)}</button><button class="icon-button" id="reset-view" aria-label="Reset view" title="Reset view">${icon('reset', 16)}</button><button class="icon-button" id="table-view" aria-label="Inspect ball return and coin slot" title="Table side">${icon('local', 18)}</button><button class="icon-button" id="spin-button" aria-label="Adjust cue contact" aria-pressed="false" title="Cue contact · Hold S">${icon('target', 18)}</button><button class="icon-button" id="elevation-button" aria-label="Adjust cue elevation" aria-pressed="false" title="Cue elevation · Hold E">${icon('cue', 18)}</button><button class="icon-button" id="cue-locker-button" aria-label="Cue collection" title="Cue collection · B">${icon('trophy', 18)}</button><button class="icon-button" id="chalk-button" aria-label="Chalk cue" title="Chalk cue · C">${icon('chalk', 18)}</button><button class="icon-button" id="coin-button" aria-label="Insert coin and reset table" title="Insert coin · New rack">${icon('coin', 18)}</button><button class="icon-button" id="reset-button" hidden aria-label="New rack" title="New rack">${icon('reset', 18)}</button><button class="icon-button" id="help-button" aria-label="Show controls" title="Controls">${icon('help', 18)}</button></div>
      <div class="cue-setup" id="cue-setup" hidden><button id="tip-control" class="tip-control" aria-label="Cue contact point. Use arrow keys to adjust spin." title="Choose where the cue hits"><i id="tip-marker"></i></button><label for="cue-angle">${icon('cue', 14)} <output id="cue-angle-value">0°</output></label><input id="cue-angle" aria-label="Cue elevation" type="range" min="0" max="60" step="1" value="0" /><button id="tip-center" class="text-button">Centre</button></div><div class="power-control mouse-only"><div class="power-track"><div class="power-bar"><div id="power-fill"></div></div><input id="power" type="range" min="5" max="100" value="65" aria-label="Shot power" /></div><strong id="power-value">65<span>%</span></strong></div>
      <div class="shot-status" id="shot-status" role="status"><span class="status-dot"></span><span id="status-text">Your break</span></div>
      <div class="lock-hint mouse-only" id="lock-hint" hidden>Click to take the cue · Esc to release · C to chalk</div>
      <div class="aim-dial touch-only" id="aim-dial" role="img" aria-label="Aim dial. Turn it with one finger to rotate the cue."><div class="aim-dial-face" id="aim-dial-face"></div><span class="aim-dial-label">AIM</span></div>
      <button class="touch-engage touch-only" id="touch-engage" aria-label="Engage cue" aria-pressed="false">Engage cue</button>
      <div class="touch-power touch-only" id="touch-power" role="slider" aria-label="Shot power" aria-orientation="vertical" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" aria-disabled="true"><strong id="touch-power-value">0%</strong><div class="touch-power-track" id="touch-power-track"><div id="touch-power-fill"></div></div></div>
      <button class="touch-shoot touch-only" id="touch-shoot" aria-label="Shoot" disabled>${icon('cue', 22)}<span>Shoot</span></button>
      <div class="loading-screen" id="loading"><div class="loading-ball">8</div><h2>Chalking up.</h2><p>Preparing the table…</p></div>
    </section>
    <div class="bottom-hud">
      <div class="mode-tabs" role="group" aria-label="Opponent"><button id="mode-ai" class="selected" aria-label="Play AI" title="Play AI" aria-pressed="true">${icon('robot', 19)}</button><button id="mode-online"${onlineHidden} aria-label="Play a friend online" title="Private room" aria-pressed="false">${icon('users', 19)}</button><button id="mode-local" aria-label="Pass and play" title="Pass & play" aria-pressed="false">${icon('local', 19)}</button></div>
      <button class="shoot-button gold-button mouse-only" id="shoot-button" aria-label="Take shot" title="Take shot · Space">${icon('cue', 21)} ${icon('arrow', 16)}</button>
    </div>
  </main>
  <dialog id="main-menu" class="main-menu" aria-labelledby="menu-title">
    <div class="menu-atmosphere" aria-hidden="true"><div class="menu-light menu-light-gold"></div><div class="menu-light menu-light-teal"></div><div class="menu-grain"></div>${Array.from({ length: 12 }, (_, i) => `<i class="menu-mote" style="--i:${i}"></i>`).join('')}</div>
    <div class="menu-frame">
      <div class="menu-masthead"><div class="menu-club-mark"><span class="menu-emblem" aria-hidden="true"><span>8</span></span><span>CORNER POCKET<span>BILLIARDS & GOOD COMPANY</span></span></div><span class="menu-open-sign">TABLES OPEN</span></div>
      <section id="menu-landing" class="menu-landing" aria-labelledby="menu-title">
        <div class="menu-hero"><p class="menu-kicker"><span></span> PULL UP. CHALK UP.</p><h1 class="menu-title" id="menu-title">THE CORNER<br><span>POCKET</span><i>.</i></h1><p class="menu-tagline">Your table. Your rules.</p>
          <div class="menu-landing-actions"><button id="menu-begin" class="menu-primary"><span>Start Game</span>${icon('arrow', 25)}</button><button id="menu-resume" class="menu-resume" hidden>${icon('cue', 21)} Resume Game ${icon('arrow', 18)}</button></div>
        </div>
        <div class="menu-feature" aria-hidden="true"><div class="menu-feature-orbit"></div><div class="menu-feature-cue"></div><div class="menu-feature-ball"><span>8</span></div><div class="menu-feature-caption"><span>ONE TABLE.</span><strong>ENDLESS POSSIBILITIES.</strong></div></div>
      </section>
      <section id="menu-setup" class="menu-setup" aria-labelledby="menu-setup-title" hidden>
        <div class="menu-setup-heading"><div><button id="menu-back" class="menu-back">${icon('arrow', 17)} Back</button><p class="menu-kicker">MAKE IT YOUR GAME</p><h2 id="menu-setup-title">Set the table<span>.</span></h2></div><button id="menu-settings" class="menu-utility">${icon('settings', 19)} Settings</button></div>
        <div class="menu-mode-grid" role="group" aria-label="Game mode">
          <button id="menu-start" class="menu-mode-card" data-mode="ai" aria-pressed="true"><span class="menu-card-number">01</span><span class="menu-card-icon">${icon('cue', 30)}</span><strong>Play the House</strong><span class="menu-card-detail" id="menu-ai-description">Solo · AI opponent</span><span class="menu-card-selected">${icon('check', 16)}</span></button>
          <button id="menu-local" class="menu-mode-card" data-mode="local" aria-pressed="false"><span class="menu-card-number">02</span><span class="menu-card-icon">${icon('local', 30)}</span><strong>Pass & Play</strong><span class="menu-card-detail" id="menu-local-description">Two players · One screen</span><span class="menu-card-selected">${icon('check', 16)}</span></button>
          <button id="menu-online"${onlineHidden} class="menu-mode-card" data-mode="online" aria-pressed="false"><span class="menu-card-number">03</span><span class="menu-card-icon">${icon('users', 30)}</span><strong>Online</strong><span class="menu-card-detail" id="menu-online-description">Private room · Invite a friend</span><span class="menu-card-selected">${icon('check', 16)}</span></button>
        </div>
        <div class="menu-configuration"><label class="menu-select" for="menu-format"><span>Match format</span><select id="menu-format" aria-describedby="menu-format-note"><option value="singles">Singles · 1 vs 1</option><option value="doubles">Doubles · 2 vs 2</option></select></label><label class="menu-select" for="menu-rules"><span>Rule set</span><select id="menu-rules">${options(RULE_OPTIONS)}</select></label><label class="menu-select" for="menu-level"><span>Level</span><select id="menu-level"></select></label><label class="menu-select" id="menu-ai-options" for="menu-difficulty"><span>Difficulty</span><select id="menu-difficulty">${options(DIFFICULTY_OPTIONS.map((option) => ({ ...option, label: `${option.label} · ${option.opponent}` })))}</select></label><button id="menu-lobby"${onlineHidden} class="menu-utility">${icon('users', 19)} Online Lobby ${icon('arrow', 16)}</button></div>
        <p id="menu-format-note" class="menu-format-note" aria-live="polite">One player against the house.</p>
        <div class="menu-session-bar"><div><span>READY TO PLAY</span><strong id="menu-mode-label">Play the House</strong></div><button id="menu-session-start" class="menu-primary"><span>Start Session</span>${icon('arrow', 24)}</button></div>
        <details class="menu-records"><summary><span>${icon('trophy', 17)} House Records</span>${icon('chevron', 17)}</summary><section class="menu-scores" aria-labelledby="scores-title"><div class="menu-scores-title"><h3 id="scores-title">House records</h3><span>This device</span></div><ol id="high-scores"></ol><p class="menu-empty" id="scores-empty">Your first rack starts the story.</p></section></details>
      </section>
      <footer class="menu-footer"><span id="menu-session-note">Mouse or touch · 1–4 players</span><span>8 BALL. ALL NIGHT.</span></footer>
    </div>
  </dialog>
  <div class="toast" id="toast" role="status" aria-live="polite"></div>
  <dialog id="rules-dialog" class="club-dialog"><button class="dialog-close" data-close aria-label="Close rules">${icon('close')}</button><span class="eyebrow">THE HOUSE RULES</span><h2>Make the table yours.</h2><p class="dialog-lead">Clear your group, then pot the eight. Every rack brings a new arrangement.</p>
    <div class="instruction-grid"><div>${icon('target', 25)}<h3>Line it up</h3><p>Move the mouse left or right to aim, then click once to lock the direction.</p></div><div>${icon('mouse', 25)}<h3>Set your strike</h3><p>Hold S and move the mouse to choose tip contact. Hold E and move vertically to raise the cue. Release the key, click to lock aim, pull back, then click again to shoot. The contact and elevation buttons work on touch screens.</p></div><div>${icon('spark', 25)}<h3>Chalk & collect</h3><p>Chalk the cue for better grip on your next off-centre strike. Only the white ball collects power-ups; they appear and fade during play.</p></div></div>
    <details><summary>Table surprises ${icon('chevron', 16)}</summary><ul><li>Coloured power-ups show their effect: orange Overdrive, blue Frostbite, green Scratch shield, gold Deadeye, or purple portals. They expire if left untouched.</li><li>Each light on a block is one HP. Destroy blocks to open new paths and earn points. Purple hex blocks can curse the aiming guide.</li><li>Ramps accelerate and water or slime slows a rolling ball. A portal pickup opens a pair after your shot; it closes after the next two shots, including retained turns.</li><li>Two consecutive cue-ball scratches grant a comeback buff. Potting both groups in one shot or a run of more than four pots triggers a debuff.</li><li>Win racks to unlock five levels with gradually stronger blocks and more terrain. Crossfire, Fortress and Hex Gauntlet change the arrangement. Friends share the host’s level and room seed.</li></ul></details>
    <details><summary>Doubles · 2 vs 2 ${icon('chevron', 16)}</summary><ul><li>Scotch doubles: partners alternate every shot, including after a legal pot. Clear your team’s group, then the eight.</li><li>Seats 1 and 3 are one team; seats 2 and 4 are the other. Teammates share their ball group, score, buffs and level progression.</li><li>Play the House pairs you with an AI against two AI opponents. Pass & Play seats four people on one screen. Online seats four friends in a private room.</li></ul></details>
    <details><summary>Eight-ball & controls ${icon('chevron', 16)}</summary><ul><li>Groups are assigned by the first legal pot after the break. Pot your own balls legally to keep playing.</li><li>Hit a legal ball, then pot a ball or touch a cushion. Hitting an obstacle also counts as a legal contact and rail action; hitting the wrong numbered ball first remains a foul.</li><li>Choose the rules when a session starts. New Rules: a foul gives your opponent ball in hand anywhere on clear felt. Old Rules: a foul gives your opponent two shots, played from where the cue ball stopped, or from behind the head string after a scratch. A pot on the first shot just continues the visit, and a foul while holding two shots gives the other side one visit.</li><li>Potting the eight early, or scratching while potting it, loses the rack. An eight on the break is respotted.</li><li>For a jump, choose a low contact point and hit hard; raising the cue adds lift. For draw, use a lower-power bottom hit. A raised cue with side contact bends the path on the cloth; chalk improves grip.</li><li>Airborne balls can clear or clip other balls. Sending a ball off the table is a foul; sending the eight off loses the rack except on the break.</li><li>Hold the right mouse button, or R, and move to look around. Release to return. R + arrow keys also rotates the view. F returns to shooting view; V toggles overhead. The view eases out while balls roll.</li><li>Behind the cue, your first click takes the cue and hides the pointer so you can keep turning; Escape shows the pointer again and cancels the shot.</li><li>On touch screens, turn the aim dial, tap Engage cue, slide the power bar on the right, then tap Shoot. Tapping the table never shoots. The camera button switches between overhead and the cue view.</li><li>Arrow keys adjust aim or power; hold Shift for finer aim. S + arrows adjusts spin; E + arrows adjusts elevation. Space locks aim, then shoots. C chalks, X centres the strike, B opens your cues, and Escape cancels the shot.</li></ul></details><button class="gold-button full-button" data-close>Back to the table ${icon('arrow', 17)}</button></dialog>
  <dialog id="settings-dialog" class="club-dialog compact"><button class="dialog-close" data-close aria-label="Close settings">${icon('close')}</button><span class="eyebrow">MAKE YOURSELF AT HOME</span><h2>Settings</h2><div class="setting"><label for="difficulty">AI difficulty</label><select id="difficulty">${options(DIFFICULTY_OPTIONS)}</select></div><div class="setting"><label for="layout">Table layout</label><select id="layout">${options(LAYOUT_OPTIONS)}</select></div><div class="setting"><div><label for="quality">Graphics quality</label><p>Find the right balance for your screen.</p></div><select id="quality">${options(QUALITY_OPTIONS)}</select></div><div class="setting"><div><label for="camera">Camera</label><p>A clear view of every angle.</p></div><select id="camera"><option value="angled">Behind the cue</option><option value="overhead">Straight overhead</option></select></div><div class="setting"><div><label for="aim-guide">Aiming guide</label><p>A little help lining things up.</p></div><input id="aim-guide" type="checkbox" role="switch" checked /></div><div class="setting"><div><label for="volume">Table volume</label><p>The satisfying sound of a good shot.</p></div><input id="volume" aria-label="Table volume" type="range" min="0" max="100" value="65" /></div><div class="setting"><button id="preview-audio" class="outline-button">Preview table sounds ${icon('sound', 16)}</button><button class="icon-button" id="fullscreen" aria-label="Fullscreen" title="Fullscreen">${icon('full')}</button></div><p class="settings-footnote" id="resolution-note"></p><a class="settings-footnote credits" href="credits.html" target="_blank" rel="noopener">Asset credits ↗</a><button class="gold-button full-button" data-close>Back to the table ${icon('arrow', 17)}</button></dialog>
  <dialog id="cue-dialog" class="club-dialog cue-dialog" aria-labelledby="cue-title"><button class="dialog-close" data-close aria-label="Close cues">${icon('close')}</button><span class="eyebrow">YOUR COLLECTION</span><h2 id="cue-title">Choose your cue.</h2><p class="dialog-lead" id="cue-owner"></p><div id="cue-collection" class="cue-collection"></div><button class="gold-button full-button" data-close>Back to the table ${icon('arrow', 17)}</button></dialog>
  <dialog id="room-dialog" class="club-dialog compact"><button class="dialog-close" data-close aria-label="Close room menu">${icon('close')}</button><span class="eyebrow">BETTER WITH COMPANY</span><h2>Save a seat for your friends.</h2><p class="dialog-lead">Open a private table and share the room code. Same table. Same game. Wherever you are.</p><label class="field-label" for="player-name">YOUR NAME</label><input class="text-input" id="player-name" maxlength="22" placeholder="The name on your tab" autocomplete="nickname" value="Player" /><label class="field-label" for="room-format">NEW TABLE FORMAT</label><select id="room-format" class="room-format-select"><option value="singles">Singles · 1 vs 1</option><option value="doubles">Doubles · 2 vs 2</option></select><label class="field-label" for="room-rules">NEW TABLE RULE SET</label><select id="room-rules" class="room-format-select">${options(RULE_OPTIONS)}</select><button class="gold-button full-button" id="create-room">Open a private table ${icon('arrow', 17)}</button><div class="or-divider"><span>OR TAKE YOUR SEAT</span></div><label class="field-label" for="room-code">FRIEND’S ROOM CODE</label><div class="join-row"><input class="text-input code-input" id="room-code" maxlength="6" placeholder="ABC123" autocomplete="off" spellcheck="false" /><button class="outline-button" id="join-room">Join table ${icon('arrow', 16)}</button></div><p id="room-error" class="form-error" role="alert"></p><p class="room-note">All players need this game’s server address.<br>Room codes also seed the starting rack.</p></dialog>
  <dialog id="invite-dialog" class="club-dialog compact"><button class="dialog-close" data-close aria-label="Close invitation">${icon('close')}</button><span class="eyebrow">YOUR TABLE IS OPEN</span><h2>The next round’s on them.</h2><p class="dialog-lead">Share the room code and fill the seats at your table.</p><button class="room-ticket" id="copy-code" title="Copy room code"><small>PRIVATE TABLE · ROOM CODE</small><strong id="invite-code">------</strong><span>${icon('copy', 16)} Click to copy</span></button><button class="gold-button full-button" id="copy-link">Copy invitation link ${icon('copy', 17)}</button><p class="room-note" id="invite-rules"></p><div id="invite-roster" class="invite-roster" aria-label="Room teams and players" aria-live="polite" hidden></div><p class="room-wait"><span class="live-dot"></span><span id="invite-status">Waiting for your friend to take a seat…</span></p></dialog>
  <dialog id="reset-dialog" class="club-dialog compact"><button class="dialog-close" data-close aria-label="Cancel new rack">${icon('close')}</button><span class="eyebrow">ONE MORE ROUND?</span><h2>A fresh start.</h2><p class="dialog-lead">Start a new rack with the current game mode. This replaces the game on your table.</p><button class="gold-button full-button" id="confirm-reset">Rack them up ${icon('reset', 17)}</button><button class="text-button full-button" data-close>Keep playing</button></dialog>
  <dialog id="result-dialog" class="club-dialog compact result-dialog"><div class="result-emblem">${icon('trophy', 42)}</div><span class="eyebrow">THAT’S A RACK</span><h2 id="result-title">Beautifully played.</h2><p class="dialog-lead" id="result-message"></p><button class="gold-button full-button" id="next-level-button" hidden>Next level ${icon('arrow', 17)}</button><button class="outline-button full-button" id="rematch-button">Another round ${icon('reset', 17)}</button><button class="text-button full-button" data-close>Admire the table</button></dialog>
  `;
}
